name: Test Sessions

on:
  push:
    branches:
      - main

jobs:
  test-sessions:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Install Deno
        run: curl -fsSL https://deno.land/install.sh | sh

      - name: Run Cypress tests
        uses: cypress-io/github-action@v2
        with:
          working-directory: ./test
          start: /home/runner/.deno/bin/deno run -A ./server.ts
          config-file: cypress/integration/sessions.spec.js
          wait-on: 'http://localhost:8002'
          browser: chrome
          headless: true