name: Test Sessions

on:
  pull_request:
    types:
      - synchronize
  push:
    branches:
      - main

jobs:
  check-code-quality:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Setup Deno
        uses: denoland/setup-deno@v1
      - name: Lint
        run: deno lint
      - name: Typecheck
        run: deno task typecheck

  test-memory-session-store:
    runs-on: ubuntu-latest
    env:
      STORE: memory
    permissions:
      contents: read # Needed to clone the repository
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Run integration tests
        uses: ./.github/workflows/cypress-test.yml

  test-redis-session-store:
    runs-on: ubuntu-latest
    env:
      STORE: redis
    permissions:
      contents: read # Needed to clone the repository
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Setup Redis
        uses: supercharge/redis-github-action@1.4.0
        with:
          redis-version: 7
      - name: Run integration tests
        uses: ./.github/workflows/cypress-test.yml

  test-mongo-session-store:
    runs-on: ubuntu-latest
    env:
      STORE: mongo
    permissions:
      contents: read # Needed to clone the repository
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Setup MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: 6.0
      - name: Run integration tests
        uses: ./.github/workflows/cypress-test.yml
