name: Test Sessions

on:
  pull_request:
    types:
      - synchronize
  push:
    branches:
      - main

jobs:
  check-code-quality:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Setup Deno
        uses: denoland/setup-deno@v1
      - name: Lint
        run: deno lint
      - name: Typecheck
        run: deno task typecheck

  test-memory-session-store:
    runs-on: ubuntu-latest
    env:
      STORE: memory
    permissions:
      contents: read # Needed to clone the repository
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Setup Deno
        uses: denoland/setup-deno@v1
      - name: Run Cypress tests
        uses: cypress-io/github-action@v2
        with:
          working-directory: ./test
          start: deno run -A ./server.ts
          spec: cypress/integration/sessions.spec.js
          wait-on: 'http://localhost:8002'
          browser: chrome
          headless: true

  test-redis-session-store:
    runs-on: ubuntu-latest
    env:
      STORE: redis
    permissions:
      contents: read # Needed to clone the repository
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Setup Deno
        uses: denoland/setup-deno@v1
      - name: Setup Redis
        uses: supercharge/redis-github-action@1.4.0
        with:
          redis-version: 7
      - name: Run Cypress tests
        uses: cypress-io/github-action@v2
        with:
          working-directory: ./test
          start: deno run -A ./server.ts
          spec: cypress/integration/sessions.spec.js
          wait-on: 'http://localhost:8002'
          browser: chrome
          headless: true

  test-mongo-session-store:
    runs-on: ubuntu-latest
    env:
      STORE: mongo
    permissions:
      contents: read # Needed to clone the repository
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Setup Deno
        uses: denoland/setup-deno@v1
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: 6.0
      - name: Run Cypress tests
        uses: cypress-io/github-action@v2
        with:
          working-directory: ./test
          start: deno run -A ./server.ts
          spec: cypress/integration/sessions.spec.js
          wait-on: 'http://localhost:8002'
          browser: chrome
          headless: true
