name: 'Cypress Tests'
description: 'Checkout, setup, and run cypress tests'
runs:
  using: "composite"
  steps:
    - name: Clone repository
      uses: actions/checkout@v2
    - name: Setup Deno
      uses: denoland/setup-deno@v1
    - name: Run Cypress tests
      uses: cypress-io/github-action@v2
      with:
        working-directory: ./test
        start: deno run -A ./server.ts
        spec: cypress/integration/sessions.spec.js
        wait-on: 'http://localhost:8002'
        browser: chrome
        headless: true
